### ISSUE TITLE
Suggestion: Wherever possible, use logging lib instead of print.

### ISSUE THREAD

**Issue by ldunham1** [Midnaut/Acid-Picker#2]
https://github.com/Midnaut/Acid-Picker/blob/39c9e0073ba95dcfb18b71ebaea2af1af40547ac/Picker%20DEV/acid_picker.py#L120

Python's logging library is a very powerful and convenient alternative to print and makes it much easier to convey warnings, errors etc.

**Comment by Midnaut** [comment]
First time having a go with the logging but very easy once you get the hang of it, thanks again 👍

**Comment by ldunham1** [comment]
Awesome, glad to hear it :)
