### ISSUE TITLE
Suggestion: Use dict.get() to simplify the if statement.

### ISSUE THREAD

**Issue by ldunham1** [Midnaut/Acid-Picker#3]
https://github.com/Midnaut/Acid-Picker/blob/39c9e0073ba95dcfb18b71ebaea2af1af40547ac/Picker%20DEV/acid_picker.py#L157

`if 'super_sets' in settings_data.get('config_advanced', []):`
Personally, I think it reads a little easier.

https://www.tutorialspoint.com/python/dictionary_get.htm#:~:text=Python%20dictionary%20method%20get(),then%20returns%20default%20value%20None.

**Comment by Midnaut** [comment]
Bit of a common response here, but splitting onto different lines in my head made this more digestible.
That being said this is a neater solution. Thanks again :)

**Comment by ldunham1** [comment]
No worries, readability is absolutely key :)
Personally, I push for readability over pretty much anything else ;)
