### ISSUE TITLE
Suggestion: Simplify if statement using truthy test.

### ISSUE THREAD

**Issue by ldunham1** [Midnaut/Acid-Picker#4]
https://github.com/Midnaut/Acid-Picker/blob/3ada0e274ea374a7d4882ba5cc2c89c8583a8b29/Picker%20DEV/acid_picker.py#L263

Suggestion to use;
`if picker_namespace:`
instead for "improved" readability (making use of truthy checks).

Apologies if you already know, I thought I would add for context.
In python, equality testing (`==`, `!=`) is different to using the `is` operator (https://www.geeksforgeeks.org/difference-operator-python/).
In this case from context, you're checking to see that you have a non-empty string. In reality is checking that your variable is "truthy" (https://docs.python.org/2.4/lib/truth.html).

As you dont completely need to check that its a string and the string has content, using `if picker_namespace:` should be easier to digest, and thanks to the variable name, just as understandable.
IF you do want to check its a string with content though;

`if isinstance(picker_namespace, basestring) and len(picker_namespace) > 0:`

Bear in mind `basestring` is NOT available in python 3, instead you would use `str`, or better yet, a module like `six` for compatibility.

**Comment by Midnaut** [comment]
While I was writing this, I had it inside my head that doing those explicit tests would be more readable for someone learning off of this, but after these suggestions I think it's always going to be better to write it out a bit more respecting the readers ability to learn fast. Thanks again.

Also all of my scripts that run off a DCC are almost invariably in Python 2.7, as far as i can tell that is the native that they all use while the VFX standard remains lagging https://vfxplatform.com/ as far as I can tell though, 3 will be the new standard pretty soon!
