### ISSUE TITLE
Suggestion: maya.cmds.button command arg accepts python callables.

### ISSUE THREAD

**Issue by ldunham1** [Midnaut/Acid-Picker#5]
https://github.com/Midnaut/Acid-Picker/blob/3ada0e274ea374a7d4882ba5cc2c89c8583a8b29/Picker%20DEV/acid_picker.py#L298

maya.cmds.button should be able to accept a python callable (function).
There are multiple ways to provide this, with some of the most popular being;
```
# lambda
for _ in ...:
    func = lambda _cn:control_name: acid_picker.modified_select(name=namespace_prefix + _cn)
    cmds.button(label, command=func)
```

```
# functools.partial
from functools import partial
for _ in ...:
    func = partial(acid_picker.modified_select, name=namespace_prefix + control_name)
    cmds.button(label, command=func)
```

```
# closure/nested function
for _ in ...:
    def func():
        acid_picker.modified_select(name=namespace_prefix + control_name)
    cmds.button(label, command=func)
```

+ more.

Whilst some might look more confusing than others, they're all relatively common but are usually best used in different circumstances (and sometimes due to preference). 
Usually, we just pick the one that is the most readable.

**Comment by Midnaut** [comment]
Hey, that's a good tip, and I already use partials for myself too. This project was supposed to be a bit of an open learning resource to newer developers so I went with the command string. If partials are generally used more widely though that's a simple change.
